version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
      - aws s3 cp build/ $s3_bucket --recursive 
      #- aws cloudfront create-invalidation --distribution-id E1RAAMNVLGH7GI --paths '/*'